In [1]:
import numpy as np

In [2]:
arr =np.array([10,20,30,40])
arr

array([10, 20, 30, 40])

In [3]:
arr2 = np.array([10,3.14,20,30])
arr2

array([10.  ,  3.14, 20.  , 30.  ])

In [4]:
arr3 =np.array([10,20,'a'])
arr3

array(['10', '20', 'a'], dtype='<U21')

In [5]:
arr4 =np.array([10,20,30])
type(arr4)

numpy.ndarray

In [6]:
arr4.size

3

In [7]:
arr4.shape

(3,)

In [8]:
arr4.ndim

1

In [9]:
arr2d =np.arange(1,13).reshape((4,3)) # reshape((rows,column))
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
arr2d.ndim

2

In [11]:
arr2d.shape


(4, 3)

In [12]:
arr2d.size

12

In [13]:
arr3d =np.arange(1,25).reshape((2,4,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [14]:
arr4d = np.arange(1,73).reshape((3,2,4,3))
arr4d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]],


       [[[25, 26, 27],
         [28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45],
         [46, 47, 48]]],


       [[[49, 50, 51],
         [52, 53, 54],
         [55, 56, 57],
         [58, 59, 60]],

        [[61, 62, 63],
         [64, 65, 66],
         [67, 68, 69],
         [70, 71, 72]]]])

In [15]:
arr5d = np.arange(1,121).reshape((2,3,2,5,2))
print(arr5d)
print(arr5d.shape)

[[[[[  1   2]
    [  3   4]
    [  5   6]
    [  7   8]
    [  9  10]]

   [[ 11  12]
    [ 13  14]
    [ 15  16]
    [ 17  18]
    [ 19  20]]]


  [[[ 21  22]
    [ 23  24]
    [ 25  26]
    [ 27  28]
    [ 29  30]]

   [[ 31  32]
    [ 33  34]
    [ 35  36]
    [ 37  38]
    [ 39  40]]]


  [[[ 41  42]
    [ 43  44]
    [ 45  46]
    [ 47  48]
    [ 49  50]]

   [[ 51  52]
    [ 53  54]
    [ 55  56]
    [ 57  58]
    [ 59  60]]]]



 [[[[ 61  62]
    [ 63  64]
    [ 65  66]
    [ 67  68]
    [ 69  70]]

   [[ 71  72]
    [ 73  74]
    [ 75  76]
    [ 77  78]
    [ 79  80]]]


  [[[ 81  82]
    [ 83  84]
    [ 85  86]
    [ 87  88]
    [ 89  90]]

   [[ 91  92]
    [ 93  94]
    [ 95  96]
    [ 97  98]
    [ 99 100]]]


  [[[101 102]
    [103 104]
    [105 106]
    [107 108]
    [109 110]]

   [[111 112]
    [113 114]
    [115 116]
    [117 118]
    [119 120]]]]]
(2, 3, 2, 5, 2)


In [16]:
arr6d = np.arange(1,145).reshape((2,2,2,3,3,2))
print(arr6d)
print(arr6d.shape)


[[[[[[  1   2]
     [  3   4]
     [  5   6]]

    [[  7   8]
     [  9  10]
     [ 11  12]]

    [[ 13  14]
     [ 15  16]
     [ 17  18]]]


   [[[ 19  20]
     [ 21  22]
     [ 23  24]]

    [[ 25  26]
     [ 27  28]
     [ 29  30]]

    [[ 31  32]
     [ 33  34]
     [ 35  36]]]]



  [[[[ 37  38]
     [ 39  40]
     [ 41  42]]

    [[ 43  44]
     [ 45  46]
     [ 47  48]]

    [[ 49  50]
     [ 51  52]
     [ 53  54]]]


   [[[ 55  56]
     [ 57  58]
     [ 59  60]]

    [[ 61  62]
     [ 63  64]
     [ 65  66]]

    [[ 67  68]
     [ 69  70]
     [ 71  72]]]]]




 [[[[[ 73  74]
     [ 75  76]
     [ 77  78]]

    [[ 79  80]
     [ 81  82]
     [ 83  84]]

    [[ 85  86]
     [ 87  88]
     [ 89  90]]]


   [[[ 91  92]
     [ 93  94]
     [ 95  96]]

    [[ 97  98]
     [ 99 100]
     [101 102]]

    [[103 104]
     [105 106]
     [107 108]]]]



  [[[[109 110]
     [111 112]
     [113 114]]

    [[115 116]
     [117 118]
     [119 120]]

    [[121 122]
     [123 124]
     [125 

### Number of values inside reshape() = number of dimensions.
### Product of those values = total number of elements.

In [17]:
arr3 =np.arange(1,43).reshape((6,7))
arr3

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])

In [18]:
arr3[[0,2,5]] # arr[[no.of each rows which you want]]


array([[ 1,  2,  3,  4,  5,  6,  7],
       [15, 16, 17, 18, 19, 20, 21],
       [36, 37, 38, 39, 40, 41, 42]])

In [19]:
arr3[:,[0,2,5]] # arr[[all rows : ,no of columns which you want]]

array([[ 1,  3,  6],
       [ 8, 10, 13],
       [15, 17, 20],
       [22, 24, 27],
       [29, 31, 34],
       [36, 38, 41]])

In [20]:
arr3[:,-1] # arr[[:only last column]]   # all rows + ONLY last column

array([ 7, 14, 21, 28, 35, 42])

In [21]:
arr3[1:4,1:4] #arr[[start rows:end row ,start column : end column]]

array([[ 9, 10, 11],
       [16, 17, 18],
       [23, 24, 25]])

In [22]:
arr3[:,:-1]  #not include last column  # all rows + all columns EXCEPT last

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27],
       [29, 30, 31, 32, 33, 34],
       [36, 37, 38, 39, 40, 41]])