In [4]:
import numpy as np

In [5]:
np.random.random()


0.4492969609252654

In [6]:
team1=np.random.randint(0,36,20)
team1

array([ 9, 16, 26, 31, 17, 26,  9,  1, 14, 18, 34, 32, 20, 10, 27, 29,  7,
       24, 12, 15], dtype=int32)

In [7]:
np.random.randint(0,36,(4,3))

array([[35, 32, 31],
       [ 4, 30,  5],
       [14,  0, 21],
       [13, 25, 30]], dtype=int32)

In [8]:
np.random.seed(75)
np.random.randint(0,100,1)

array([19], dtype=int32)

In [9]:
np.random.rand()

0.7563298857816358

In [10]:
np.random.randn(10)

array([-1.1378538 , -1.37925852, -1.26922007,  2.98437224,  0.04038575,
       -0.67221661,  0.38703737,  2.39680022,  0.68111417,  1.4500866 ])

In [11]:
dice=np.arange(1,7)

In [12]:
np.random.choice(dice,1)

array([5])

In [13]:
dice

array([1, 2, 3, 4, 5, 6])

In [14]:
np.random.permutation(dice)

array([2, 3, 4, 6, 1, 5])

In [15]:
np.sin(np.radians(30))

np.float64(0.49999999999999994)

In [16]:
np.radians(np.sin(3*3.14))


np.float64(8.339082966900845e-05)