In [1]:
import numpy as np

In [2]:
arr =np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2d =arr.reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Basic Function

In [4]:
arr2d.ravel() #it print element row wise

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2d.flatten('F') # it print element column wise

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [6]:
arr2d.flatten('c') # c style it print element row wise

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(1,3,5) # equally divide all parts between 1 to 3

array([1. , 1.5, 2. , 2.5, 3. ])

Mathematical Function

In [8]:
arr1 = np.arange(1,10).reshape((3,3))
arr2 = np.arange(3,12).reshape((3,3))
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [9]:
np.add(arr1,arr2)

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [10]:
arr1 + arr2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [11]:
np.subtract(arr2, arr1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [12]:
arr2 - arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [13]:
np.multiply(arr1,arr2)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [14]:
arr1 * arr2

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [15]:
np.divide(arr1,arr2)

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [16]:
arr1 / arr2

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [17]:
arr3 = np.array([10,20,30])
arr3

array([10, 20, 30])

In [18]:
arr1 + arr3 # broadcasting  column no should be same


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [19]:
arr1,arr3

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([10, 20, 30]))

In [20]:
np.dot(arr1,arr2)  #matrix multiplication

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [21]:
np.sqrt(arr1) # square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [22]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [23]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [25]:
arr1.min()

np.int64(1)

In [26]:
arr1.max() # it gives maximum value

np.int64(9)

In [27]:
arr2.argmax() #it gives maximum value index

np.int64(8)

In [28]:
arr2.argmin()

np.int64(0)

Calculation

In [29]:
arr1,arr2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [30]:
np.concatenate([arr1,arr2]) #no of column should be same

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
np.concatenate([arr1,arr2],axis =1) # no of row should be same    axis=0 → rows   ,  axis=1 → columns

array([[ 1,  2,  3,  3,  4,  5],
       [ 4,  5,  6,  6,  7,  8],
       [ 7,  8,  9,  9, 10, 11]])

Spliting

In [32]:
np.split(arr1,3,axis=0)# we can split into equal part

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]