In [1]:
import numpy as np

In [2]:
np.random.random()

0.1271376598283369

In [3]:
team1=np.random.randint(0,36,20)
team1

array([20,  8, 21,  4, 18,  8, 29, 14, 23, 16, 25,  5, 23,  9, 27, 12, 23,
       18, 31, 26], dtype=int32)

In [4]:
np.random.randint(0,36,(4,3))

array([[ 8, 35,  4],
       [ 0, 24, 14],
       [27,  5, 21],
       [12, 18, 17]], dtype=int32)

In [5]:
np.random.seed(10)
np.random.randint(0,100,1)

array([9], dtype=int32)

In [6]:
np.random.rand()

0.29876115188562824

In [7]:
np.random.randn(10)

array([-2.93119247, -0.27828276,  0.29986131,  1.19449472, -0.90561048,
       -0.89808938,  0.45187984, -0.85947418, -0.53479453,  1.03287114])

In [8]:
dice =np.arange(0,7)

In [9]:
dice

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
np.random.choice(dice,1)

array([0])

In [11]:
np.random.permutation(dice)

array([4, 5, 6, 0, 1, 2, 3])

In [12]:
np.sin(np.radians(30))

np.float64(0.49999999999999994)